### ISSUE TITLE
[Design] Strange Fade on Perscription To Right

### ISSUE THREAD

**Issue by ifasoldt** [aoristdev/orderlyaid#85]
Doesn't go away no matter what I do
![Uploading Screen Shot 2017-04-22 at 4.40.50 PM.png…]()

**Comment by davegregg** [comment]
I can't see this image.

**Comment by ifasoldt** [comment]
<img width="708" alt="screen shot 2017-04-22 at 4 40 50 pm" src="https://cloud.githubusercontent.com/assets/18588427/25310003/942319bc-27a8-11e7-9e10-b322e051e625.png">

**Comment by strempe** [comment]
There are two ways to bring the prescription boxes into focus - 1. clicking the box  2. clicking the pill shaped label at the top.
It's an intentional UI decision to help the user focus on one prescription. When the page had all the prescriptions in focus with instructions, cautions, and notes, the amount of text was uncomfortable. Fading out the panels is one way to avoid throwing in a lot of info in a small space. Also, hopefully, giving the user a little more control over what they see. @ifasoldt
